name: WolfLang
version: 1.0.0
main: dev.wolfstudios.wolflang.WolfLangPlugin
api-version: '${apiVersion}'
folia-supported: true
depend: []
softdepend: [PlaceholderAPI]

commands:
  wlang:
    description: Change your language
    aliases: [language, lang]
    usage: /<command> [code|auto|gui]
  wlangreload:
    description: Reload WolfLang config
    aliases: [wlreload, wolflangreload]
    permission: wolflang.reload
